config/routes.rb
Rails.application.routes.draw do
  get 'first/about'
  get 'locations/new'
  get 'home/location_list'

  resources :locations, :home
  get '/static_pages/index'
  get '/static_pages/about'
  get '/static_pages/contact'
  post '/static_pages/thank_you'

  root 'static_pages#index'

  get 'location_list/:id' => 'home#location_list'
  get '/static_pages/contact' => 'thank_you#static_pages'

end

app/models/location.rb
class Location < ActiveRecord::Base
  validates_presence_of :email, :title, :latitude, :longitude
  validates :email, format: /\A\w+\S+[@]\w+\S+[.]\w+\S+\z/ 
end

# /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/ could be another regular expression for the email-adress, but not neccesary

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/first_controller.rb
class FirstController < ApplicationController
  def about
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def location_list	
	end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    if params[:q]
      search_term = "%#{params[:q]}%"
      @locations = Location.where("title like ? or notes like ?", search_term, search_term)
    else
      @locations = Location.all
    end
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:title, :image_url, :email, :latitude, :longitude, :permission, :notes)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
  end

  def landing_page
  end

  def thank_you
    @name = params[:name]
    @email = params[:email]
    @message = params[:message]
    UserMailer.contact_form(@email, @name, @message).deliver_now
    #ActionMailer::Base.mail(:from => @email,
    #    :to => 'linberg.dev@gmail.com',
    #    :subject => "A new contact form message from #{@name}",
    #    :body => @message).deliver_now
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/first_helper.rb
module FirstHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/first/about.html.erb
<h1>edible hood</h1>

<h2>Wir finden, dass öffentliche Grünflächen mit essbaren Pflanzen bestückt werden sollen. Die ganze Stadt könnte irgendwann ein großer Gemeinschaftsgarten werden, in dem alle fröhlich zusammen regionales, frisches Gemüse anbauen und ernten. In diesen urbanen Gemeinschaftsgärten können sich Leute aus der Nachbarschaft kennenlernen und vernetzen, gemeinsam Zeit verbringen oder sich einfach zur Erholung aufhalten... Wenn auch du Lust darauf hast, an unserer Utopie mitzubauen, dann trage Infos zu potentiell bepflanzbaren Grünflächen in deiner Hood in unsere Karte ein und werde Teil unseres Nachbarschafts-Garten-Netzwerks  ;) </h2>


<p>Wenn du deine Info in die Karte eintragen willst, klick auf <%= link_to "New Location", locations_new_path %> </p>

<p>Wenn du die Liste der bereits vorhandenen Grünflächen sehen willst, klick auf <%= link_to "List Locations", locations_path %> </p>


Find me in app/views/first/about.html.erb

app/views/home/location_list.html.erb
location_list.html.erb

<p id="notice"><%= notice %></p>

<h1>edible hood</h1>

<div id="map" style="height: 500px; width: 700px"></div>


  <script>
    function initMap() {

  var map = new google.maps.Map(document.getElementById('map'), {
    zoom: 14,
    center: myLatLng
  });

  </script>

  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCgfmYcnR_ODZPi8R2Q4s-LR2L5uX3gfMo&callback=initMap"
  async defer></script>


<h2>Listing Locations</h2>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.title %></td>
        <td><%= image_tag location.image_url, height: 100%></td>
        <td><%= location.email %></td>
        
        <td>  </td>
        <td><%= location.latitude %></td>

        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>






<%= link_to 'New Location', new_location_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ediblehood</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>
<body>

    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div> <!--end navbar-header-->
          <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li><a href="/"> Home&nbsp;</a></li>
              <li><a href="/static_pages/about"> About&nbsp;</a></li>
              <li><a href="/locations"> Locations&nbsp;</a></li>
              <li><a href="/static_pages/contact"> Contact&nbsp;</a></li>
            </ul>
          </div> <!--end navbar-collapse-->
       </div> <!--end container-fluid-->
    </nav>


<%= yield %>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

<script type="text/javascript">
  var $root = $('html, body');
    $('.navbar-nav a').click(function() {
        var href = $.attr(this, 'href');
        $root.animate({
            scrollTop: $(href).offset().top
        }, 500, function () {
            window.location.hash = href;
        });
        return false;
    });
</script>

</body>
</html>

app/views/layouts/landing_page.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ediblehood</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/locations/_form.html.erb
<div class="col-md-8" id="map" style="height: 500px; width: 700px"></div>
    <script>
    function initMap() {
  var myLatLng = {lat: <%= @location.latitude || 52.499138 %>, lng: <%= @location.longitude || 13.449807 %>};
  var map = new google.maps.Map(document.getElementById('map'), {
    zoom: 14,
    center: myLatLng
  });

  var marker = new google.maps.Marker({
    position: myLatLng,
    map: map,
    draggable: true,
  });

  function handleDragend(mouseEvent) {
    $('#location_latitude').val(marker.getPosition().lat())
    $('#location_longitude').val(marker.getPosition().lng())
  }
  function handleDrag(mouseEvent) {
    $('#coordinates').html(marker.getPosition().lat() + ", " + marker.getPosition().lng())
  }

  marker.addListener('dragend', handleDragend);
  marker.addListener('drag', handleDrag);

  var point = marker.getPosition();
  map.panTo(point);

  localStorage['lastLat'] = point.lat();
  localStorage['lastLng'] = point.lng();
}
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCgfmYcnR_ODZPi8R2Q4s-LR2L5uX3gfMo&callback=initMap"
    async defer></script>
<br>
Your current position
<div id="coordinates">

</div>

<div class="new-location form-group">
<%= form_for(@location) do |f| %>

  <div class="col-md-3 col-xs-6 form-group">
    <!--<%=  f.label :title %>-->
    <%= f.text_field :title, class: "form-control", placeholder: "Title" %>
  </div>

<div class="col-md-3 col-xs-6 form-group field">
  <!--<%= f.label :email %>-->
  <%= f.text_field :email, class: "form-control", placeholder: "Email" %>
</div>

<div class="col-md-3 col-xs-6 form-group field">
  <%= f.hidden_field :latitude %>
  <%= f.hidden_field :longitude %>
</div>

<div class="col-md-3 col-xs-6 form-group field">
  <!--<%= f.label :growing_status %>-->
  <%= f.text_field :growing_status, class: "form-control", placeholder: "Growing Status" %>
</div>

<div class="col-md-3 col-xs-6 form-group field">
  <!--<%= f.label :permission %>-->
  <%= f.text_field :permission, class: "form-control", placeholder: "Permission" %>
</div>

<div class="col-md-3 col-xs-6 form-group field">
  <!--<%= f.label :notes %>-->
  <%= f.text_field :notes, class: "form-control", placeholder: "Notes"  %>
</div>

<div class="col-md-3 col-xs-6 form-group field">
  <!-- <%= f.label :image_url %> -->
  <%= f.text_field :image_url, class: "form-control", placeholder: "Image URL"  %>
</div>


  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%
      if @location.id
        submit_label = "Update"
      else
        submit_label = "Create new Location"
      end
    %>

    <%= f.submit submit_label, class: "btn btn-success" %>
  </div>

<% end %>
</div><!--end div newlocation-->

app/views/locations/_search_form.html.erb
<div class="row">
  <div class="col-lg-6 col-xs-4">
  <%= form_tag("", method: "get") do %>
    <div class="input-group">
      <%= text_field_tag(:q, params[:q], class: "form-control", placeholder: "Search") %>
      <span class="input-group-btn">
        <button class="btn btn-secondary" type="submit"><i class="glyphicon glyphicon-search"></i></button>
      </span>
    </div>
  </div>
<%= link_to("X", locations_path, class: "btn btn-danger") if params[:q] %>
</div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form' %>


	<%= link_to 'Show', @location, class: "btn btn-default" %> 



	<%= link_to 'Back', locations_path, class: "btn btn-default" %>

app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>

<div class="locations-container">
    <%= link_to 'Add Location', new_location_path, class: "btn btn-default pull-left locations-button" %>
    <%= render 'search_form' %>

  <div class="locationsmap" style="width: 800px; height: 600px">
  </div>
</div><!--end locations-container-->


<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCgfmYcnR_ODZPi8R2Q4s-LR2L5uX3gfMo"></script>

<script>
var locations = [];
<% for location in @locations %>
  locations.push({
    lat: <%= location.latitude %>,
    lng: <%= location.longitude %>,
    id: "<%= location.id %>",
    title: "<%= location.title %>",
    imageUrl: "<%= location.image_url %>",
    createdAt: "<%= location.created_at %>",
    permission: "<%= location.permission %>",
    growingStatus: "<%= location.growing_status %>"
  });
<% end %>
buildMap(locations);
</script>

app/views/locations/new.html.erb
<h1>New Location</h1>
<%= render 'form' %>


<%= link_to 'Back', locations_path, class: "btn btn-default" %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<%= render 'form' %>

<%= link_to 'Edit', edit_location_path(@location), class: "btn btn-default"%> 
<%= link_to 'Back', locations_path, class: "btn btn-default" %>

app/views/static_pages/about.html.erb
<div class="about-container col-md-3 col-xs-6">
  <div class="transbox">
    <h1><b>edible hood</b></h1>
    <h3>Wir finden, dass öffentliche Grünflächen mit essbaren Pflanzen bestückt werden sollen. Die ganze Stadt könnte irgendwann ein großer Gemeinschaftsgarten werden, in dem alle fröhlich zusammen regionales, frisches Gemüse anbauen und ernten.
    <br>
    <br>
    In diesen urbanen Gemeinschaftsgärten können sich Leute aus der Nachbarschaft kennenlernen und vernetzen, gemeinsam Zeit verbringen oder sich einfach zur Erholung aufhalten... Wenn auch du Lust darauf hast, an unserer Utopie mitzubauen, dann trage Infos zu potentiell bepflanzbaren Grünflächen in deiner Hood in unsere Karte ein und werde Teil unseres Nachbarschafts-Garten-Netzwerks  ;) </h3>
 </div>

<div class="about-text">
	<h4>Wenn du deine Info in die Karte eintragen willst, klick auf <%= link_to "New Location", locations_new_path, class: "btn btn-primary" %> </h4>

<h4>Wenn du die Liste der bereits vorhandenen Grünflächen sehen willst, klick auf <%= link_to "List Locations", locations_path, class: "btn btn-primary" %> </h4>
</div>
</div>

app/views/static_pages/contact.html.erb
<div class="contact" id="contact"><h1>Contact us</h1>

<%= flash[:notice] %>

<%= form_tag("/static_pages/thank_you/") do %>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <div class="form-group">
      <%= label_tag :name, "Name" %>
      <%= text_field_tag :name, nil, class: "form-control", placeholder: "Enter Name", required: "required" %>
    </div>
    <div class="form-group">
      <%= label_tag :email, "Email Address" %>
      <%= email_field_tag :email, nil, class: "form-control", placeholder: "Enter Email", required: "required" %>
    </div>
    <div class="form-group">
      <%= label_tag :message, "Message" %>
      <%= text_area_tag :message, nil, class: "form-control", placeholder: "Enter Message", required: "required" %>

    </div>
       <%= submit_tag "Send", class:  "btn btn-default" %>
    </div>
</div>

<% end %>


<!--we need to build a test for the contact form. I've found some useful information on http://everydayrails.com/2012/03/19/testing-series-rspec-models-factory-girl.html .. should we create a new file in models for contact and write the tests like: require 'spec_helper'

describe Contact do
  it "has a valid factory"
  it "is invalid without a firstname"
  it "is invalid without a lastname"
  it "returns a contact's full name as a string"
end ? -->

app/views/static_pages/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ediblehood</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>

</head>
<body>

  <div class="edhood">
  <img class="img-responsive" src="/assets/edhood.png">
  </div>

<%= yield %>

</body>

<footer id="colophone" class="site-footer">
  &copy; 2016 Bergen &amp; Santro
</footer>

</html>

app/views/static_pages/thank_you.html.erb
<!DOCTYPE html>
<html lang="en">
  <body>

  	<h1> Thank you for contacting us! 
  	</h1>

  </body>
  </html>